name: Linux Build, Test

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            compiler: gcc
            runner: ubuntu-26.04
            preset: lin-x64-gcc-release
          - arch: x64
            compiler: clang
            runner: ubuntu-26.04
            preset: lin-x64-clang-release
          - arch: arm64
            compiler: gcc
            runner: ubuntu-26.04-arm
            preset: lin-arm64-gcc-release
          - arch: arm64
            compiler: clang
            runner: ubuntu-26.04-arm
            preset: lin-arm64-clang-release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clang 22
        if: contains(matrix.compiler, 'clang')
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22

      - name: Setup vcpkg and Cache
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build Project
        run: cmake --build build/${{ matrix.preset }} -j$(nproc)

      - name: Run Tests
        run: |
          ctest --test-dir build/${{ matrix.preset }} --output-on-failure
