name: macOS Build, Test

on:
  workflow_dispatch:

jobs:
  build-test-coverage:
    name: macOS (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-26
            arch: x64
            preset: mac-x64-release
          - os: macos-latest
            arch: arm64
            preset: mac-arm64-release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup vcpkg and Cache
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        run: cmake --preset ${{ matrix.preset }}

      - name: Build Project
        run: |
          cmake --build build/${{ matrix.preset }} --parallel

      - name: Run Tests with CTest
        run: |
          ctest --test-dir build/${{ matrix.preset }} --output-on-failure
