name: Windows Build, Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows / ${{ matrix.compiler }} ${{ matrix.cmake_arch || '' }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - compiler: msvc
            preset: win-x64-msvc26-release
            cmake_arch: x64

          - compiler: clang
            preset: win-x64-clang-release

          - compiler: mingw
            preset: win-x64-mingw-release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install LLVM and Clang
        if: matrix.compiler == 'clang'
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: '21'

      - name: Setup MSYS2
        if: matrix.compiler == 'mingw'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-gcc-libs
            mingw-w64-ucrt-x86_64-binutils

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake (MSVC)
        if: matrix.compiler == 'msvc'
        shell: pwsh
        run: cmake --preset ${{ matrix.preset }}

      - name: Configure CMake (Clang)
        if: matrix.compiler == 'clang'
        shell: pwsh
        run: cmake --preset ${{ matrix.preset }}

      - name: Configure CMake (MinGW)
        if: matrix.compiler == 'mingw'
        shell: pwsh
        run: |
          $env:PATH = "C:\msys64\ucrt64\bin;$env:PATH"

          cmake --preset ${{ matrix.preset }}

      - name: Build Project
        shell: pwsh
        run: |
          if ("${{ matrix.compiler }}" -eq "mingw") {
            $env:PATH = "C:\msys64\ucrt64\bin;$env:PATH"
          }
          cmake --build build/${{ matrix.preset }} --config Release --parallel

      - name: Run Tests
        shell: pwsh
        run: |
          if ("${{ matrix.compiler }}" -eq "mingw") {
            $env:PATH = "C:\msys64\ucrt64\bin;$env:PATH"
          }
          ctest --test-dir build/${{ matrix.preset }} -C Release --output-on-failure
