name: Windows ARM64 MSVC Build, Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Windows ARM64 MSVC
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Configure CMake
        shell: pwsh
        run: cmake --preset win-arm64-msvc-release

      - name: Build Project
        run: cmake --build build/win-arm64-msvc-release --config Release --parallel

      - name: Run Tests
        run: ctest --test-dir build/win-arm64-msvc-release -C Release --output-on-failure
